# Numpy

Numpy is a type of array(c++ type of array not like a list)  
nd-array -> n-dimensional array

### Creating different type of Numpy arrays

In [1]:
import numpy as np

In [2]:
np1 = np.array([0, 1, 2, 3, 4]) # Creating a Numpy array
np1

array([0, 1, 2, 3, 4])

In [3]:
np1.shape # see the shape of the array

(5,)

In [4]:
np1 = np.arange(4) # arange() used to create arrays in sequential order
np1

array([0, 1, 2, 3])

In [5]:
np1 = np.arange(4, 50, 3) # arange(begin, end, step)
np1

array([ 4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

In [6]:
np1 = np.zeros((5)) # zeros() used to create a array of zeroes, Always pass in a tuple of values as the shape
np1

array([0., 0., 0., 0., 0.])

In [7]:
np1 = np.zeros((5, 2)) # as we can see float values are produced.
np1

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [8]:
np1 = np.zeros((2, 7), dtype=int) # use 'dtype=int' to get zeros in integers
np1

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [9]:
np1 = np.full((2, 7), 5) # full(shape, number) used to fill the entire array of 'shape' with just 'number'
np1

array([[5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5]])

In [10]:
list1 = [1, 2, 3, 4, 5]
np1 = np.array(list1) # converting a python-list into a numpy array.
np1

array([1, 2, 3, 4, 5])

### Accessing & Slicing

When we slice an array we get a sub-array which we can use later

#### Slicing 1d arrays

In [11]:
np1 = np.array([1, 2, 3, 4, 5, 6])
print(np1[0], ",", np1[3]) # Accessing elements is similar to normal C++ arrays
print(np1[-1], ",", np1[-3])

1 , 4
6 , 4


In [12]:
np1 = np.array(["zeroth", "first", "second", "third", "fourth", "fifth"])
np1[ [0, 2, 5] ] # We can get a sub-array of the main array passing the indexes in a array form

array(['zeroth', 'second', 'fifth'], dtype='<U6')

In [13]:
np1 = np.array([50, 82,  9, 37, 26, 44, 74, 74, 13, 63])
np1[1:4] # slicing the numpy array np1[included_index:excluded_index]

array([82,  9, 37])

In [14]:
np1[1:7:2] # np1[included_index:excluded_index:step], although 'step' is optional.

array([82, 37, 44])

In [15]:
np1[::2] # by default included_index = 0, excluded_index = -1(last element).

array([50,  9, 26, 74, 13])

In [16]:
np1[3:]

array([37, 26, 44, 74, 74, 13, 63])

In [17]:
np1[-5:-1] # we can write indexes only in a ascending order i.e. excluded_index > included_index

array([44, 74, 74, 13])

<b>We can use slicing method to reverse our arrays</b>

In [18]:
np1 = np1[-1:0:-1] # start from -1(the last element) ,end at 0(the first element), -1 => take negative steps
np1

array([63, 13, 74, 74, 44, 26, 37,  9, 82])

#### Slicing nd arrays

In [19]:
np1 = np.array(
    [
        [69, 70, 14,  0, 59],
        [49,  3, 93, 63, 85],
        [51, 48, 50, 53, 86]
    ]
)
np1

array([[69, 70, 14,  0, 59],
       [49,  3, 93, 63, 85],
       [51, 48, 50, 53, 86]])

<u><b>Note:</b></u><br>
Slicing a nd array is a bit complicated  
Consider slicing the 2d array -> np1[index1:index2, index3:index4]  
Here,  
index1:index2 -> represents slicing of the (n-1)d arrays -> i.e. 1d arrays  
index3:index4 -> represents slicing of the (n-2)d arrays inside those sliced (n-1)d arrays-> i.e. 0d array elements.

In [20]:
np1[1:2, 3:4] # gives out a resultant sub-2d array

array([[63]])

In [21]:
np1[0:2, :] # gives out a resultant sub-2d array

array([[69, 70, 14,  0, 59],
       [49,  3, 93, 63, 85]])

In [22]:
np1[1, 2:4] # gives out a 1d array without the slice symbol -> ':'

array([93, 63])

In [23]:
np1[1, 2:4].shape # this is a bad shape

(2,)

In [24]:
np1[1:2, 2:4] # # gives out a 2d array although it is similar to the example above

array([[93, 63]])

In [25]:
np1[1:2, 2:4].shape # this is a good shape

(1, 2)

In [26]:
np1 = np.array(
        [[[37, 77, 63, 90, 45],
        [49, 33,  0,  7, 21],
        [62,  4, 83, 45, 51],
        [57, 83, 41, 13,  5]],

       [[ 9, 54, 10, 60, 55],
        [52, 39, 23, 71, 43],
        [37, 59, 97, 43, 19],
        [24, 78, 25, 44, 63]],

       [[39, 72, 38, 90, 75],
        [62,  1, 39, 86, 67],
        [83, 72, 66, 21, 84],
        [78, 82, 60, 50, 84]]]
)
np1

array([[[37, 77, 63, 90, 45],
        [49, 33,  0,  7, 21],
        [62,  4, 83, 45, 51],
        [57, 83, 41, 13,  5]],

       [[ 9, 54, 10, 60, 55],
        [52, 39, 23, 71, 43],
        [37, 59, 97, 43, 19],
        [24, 78, 25, 44, 63]],

       [[39, 72, 38, 90, 75],
        [62,  1, 39, 86, 67],
        [83, 72, 66, 21, 84],
        [78, 82, 60, 50, 84]]])

In [27]:
np1.shape # this is a 3d array

(3, 4, 5)

In [28]:
np1[0:2, 1:4, 2:-1]

array([[[ 0,  7],
        [83, 45],
        [41, 13]],

       [[23, 71],
        [97, 43],
        [25, 44]]])

In [29]:
np1[0:2, 1:4, 2:-1].shape

(2, 3, 2)

Shape explained:  
np1[0:2, 1:4, 2:-1] contains 2 2d arrays, 3 1d arrays inside each of those 2d arrays,  
2 0d array elements inside each of those 1d arrays hence the shape -> 2,3,2

### Numpy ufuncs (Universal functions)

In [30]:
np1 = np.array(
    [
        [31, 22, 97],
        [71, 84, 47]
    ]
)
np1

array([[31, 22, 97],
       [71, 84, 47]])

In [31]:
np1.shape  # 2 1d arrays of 3 0d elements in each 1d array

(2, 3)

In [32]:
np.sqrt(np1)

array([[5.56776436, 4.69041576, 9.8488578 ],
       [8.42614977, 9.16515139, 6.8556546 ]])

In [33]:
np.absolute(np1)

array([[31, 22, 97],
       [71, 84, 47]])

In [34]:
np.exp(np1)

array([[2.90488497e+13, 3.58491285e+09, 1.33833472e+42],
       [6.83767123e+30, 3.02507732e+36, 2.58131289e+20]])

In [35]:
np.min(np1)

22

In [36]:
np.max(np1)

97

In [37]:
np.sin(np1)

array([[-0.40403765, -0.00885131,  0.37960774],
       [ 0.95105465,  0.73319032,  0.12357312]])

In [38]:
np.cos(np1)

array([[ 0.91474236, -0.99996083, -0.92514754],
       [-0.30902273, -0.6800235 , -0.99233547]])

In [39]:
np.tan(np1)

array([[-0.44169557,  0.00885166, -0.4103213 ],
       [-3.0776204 , -1.07818381, -0.12452757]])

In [40]:
np.log(np1)

array([[3.4339872 , 3.09104245, 4.57471098],
       [4.26267988, 4.4308168 , 3.8501476 ]])

In [41]:
np1[0, 1] *= -1
np1[1, 2] *= -1

In [42]:
np.sign(np1)

array([[ 1, -1,  1],
       [ 1,  1, -1]])

### Copy vs View

In [43]:
np1 = np.array([0, 1, 2, 3, 4, 5])
np2 = np1.copy() # creates a duplicate copy
np3 = np1.view() # still linked to the parent array
np4 = np1 # still linked to the parent array

# by default if we write np_new = np_old, we are using view() which is still linked to np_old.

np1[0] = 11
print("1st:", np1, np2, np3, np4)
np2[0] = 15
print("2nd:", np1, np2, np3, np4)
np3[0] = 12
print("3rd:", np1, np2, np3, np4)
np4[0] = 20
print("4th:", np1, np2, np3, np4)

1st: [11  1  2  3  4  5] [0 1 2 3 4 5] [11  1  2  3  4  5] [11  1  2  3  4  5]
2nd: [11  1  2  3  4  5] [15  1  2  3  4  5] [11  1  2  3  4  5] [11  1  2  3  4  5]
3rd: [12  1  2  3  4  5] [15  1  2  3  4  5] [12  1  2  3  4  5] [12  1  2  3  4  5]
4th: [20  1  2  3  4  5] [15  1  2  3  4  5] [20  1  2  3  4  5] [20  1  2  3  4  5]


### numpy.reshape()

In [44]:
np1 = np.arange(1, 13, 1)
np1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [45]:
np1.shape

(12,)

In [46]:
np1.reshape(1, 12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [47]:
np1.reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [48]:
np1 = np1.reshape(2, 3, 2)

In [49]:
np1

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [50]:
np1.flatten() # can be used to flatten a nd array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [51]:
np1

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [52]:
np1 = np1.reshape(-1) # can also be used to flatten a nd array
np1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### Iterating through Numpy arrays

In [53]:
np1 = np.array([1, 2, 3 ,4, 5])
print("Iterating through 1d array: ")
for x in np1:
    print(x)
np1 = np.array(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)
print("Iterating through 2d array: ")
for x in np1: # here x is the 1d array
    for y in x: # here y is the 0d array element
        print(y)

Iterating through 1d array: 
1
2
3
4
5
Iterating through 2d array: 
1
2
3
4
5
6


<u><b>NOTE:</b></u>  
Now, a clever way to iterate through the arrays using np.nditer()
nditer() iterates through any nd-arrat to the basic 0d arrays

In [54]:
print("np1:\n",np1)
print("Iterating using np.nditer(): ")
for x in np.nditer(np1):
    print(x)

np1:
 [[1 2 3]
 [4 5 6]]
Iterating using np.nditer(): 
1
2
3
4
5
6


### Sorting Numpy arrays

we can sort in 2 ways:  
1. np_array.sort() -> this type of sort changes the array
2. np.sort(np_array) -> this just returns the sorted array, But doesn't change the array itself

In [55]:
np1 = np.array([2, 1, 3, 4, 6, 5])
np2 = np.array(["Yesh", "siri", "krish", "radha"])
np3 = np.array([True, False, True, False])
np4 = np.array([
    [
        [6, 7, 1, 9],
        [8, 3, 5, 0]
    ],
    
    [
        [9, 8, 1, 7],
        [6, 5, 4, 0]
    ]
])

In [56]:
np.sort(np1)

array([1, 2, 3, 4, 5, 6])

In [57]:
# we cannot sort a numpy array in reverse but we can do this as the following:
np_temp = np.sort(np1)
np_temp[-1:0:-1] # start from -1(the last element) ,end at 0(the first element), -1 => take negative steps

array([6, 5, 4, 3, 2])

In [58]:
np.sort(np2) # sorts according to ASCII values

array(['Yesh', 'krish', 'radha', 'siri'], dtype='<U5')

In [59]:
np.sort(np3) # False = 0 and True = 1 in binary

array([False, False,  True,  True])

In [60]:
np.sort(np4) # each 1d array is sorted (makes sense)

array([[[1, 6, 7, 9],
        [0, 3, 5, 8]],

       [[1, 7, 8, 9],
        [0, 4, 5, 6]]])

### Searching Numpy arrays

We Search Numpy arrays using np.where() function,  
np.where(condition) -> we pass in a condition and it returns a sub array of indexes containing our search result.

In [61]:
np1 = np.arange(51, 61, 1)
np1

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60])

In [62]:
x = np.where(np1 % 2 == 0)
print(x) # returns indexes of all those that match the search.

(array([1, 3, 5, 7, 9]),)


In [63]:
x[0] # the indexes of the array elements that matched the search

array([1, 3, 5, 7, 9])

In [64]:
np1[x[0]] # all the array elements that matched the search

array([52, 54, 56, 58, 60])

### Filtering Numpy arrays

Let's see in detail what's happening, but we can just use the Numpy shorthand to make this process easier  
filtered = np_array > 3 (condition)

In [65]:
np1 = np.array([1, 2, 3, 4, 5])
x = [True, False, False, True, True] # filter or mask
np1[x] # This is valid because we can pass an array of values to get multiple values as seen above

array([1, 4, 5])

In [66]:
filtered = []
for num in np1:
    if num > 3:
        filtered.append(True)
    else:
        filtered.append(False)
np1[filtered]

array([4, 5])

Now Using the Numpy shorthand (directly write the condition):

In [67]:
np1 > 3 # gives out a mask

array([False, False, False,  True,  True])

In [68]:
filt = np1 > 3 # Numpy shorthand
np1[filt]

array([4, 5])

### Generating Random numbers and Random arrays

-> One of the main use case of Numpy is to generate arrays with random numbers. Let's see how to do that

In [69]:
np.random.randint(100) #np.random.randint(high) is the basic format. Gives out a random number < high, 
# here high=100

34

In [70]:
np.random.randint(low = 100, high=500) # gives a random number between 'low' and 'high'

250

In [71]:
np.random.randint(low=100, high=500, size=(5, 5)) # gives out a nd array of size 'size' between 'low' & 'high'.

array([[108, 103, 234, 470, 131],
       [199, 487, 257, 160, 482],
       [418, 186, 221, 288, 319],
       [401, 493, 415, 156, 147],
       [493, 113, 286, 285, 111]])

In [72]:
np.random.randint(6, size=(5, 5)) # by default the first argument is for 'high'

array([[5, 3, 3, 5, 2],
       [5, 3, 2, 4, 3],
       [0, 4, 0, 0, 5],
       [0, 4, 3, 3, 5],
       [3, 3, 3, 3, 4]])

In [73]:
np.random.rand() # np.random.rand() gives out a float value

0.3316826859900296

In [74]:
np.random.rand(2, 5) # just passing in the dimensions of the nd-array we want directly

array([[0.38434088, 0.33124509, 0.4017175 , 0.1718395 , 0.31733107],
       [0.24315568, 0.95314098, 0.30077135, 0.41214044, 0.12473636]])

In [75]:
np1 = np.random.randint(50, size=10)
np1

array([18, 21, 29, 44, 18, 32, 24, 15, 11, 14])

In [76]:
np.random.choice(np1) # np.random.choice(np_array) helps pick out a random value from the np_array.

24